/**
 * doctor — diagnose a registered TEE machine.
 *
 *   tsx src/cli.ts <teeId|host>     one machine
 *   tsx src/cli.ts --worst          the most broken machines in the register
 *
 * Reads packages/reprod/out/scan.json, so it needs no keys and no network of
 * its own. Prose is added only when ZEROG_API_KEY is present, and its absence
 * changes nothing about the diagnosis.
 */
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { diagnose, verdictOf, type MachineFacts, type Finding } from "./diagnose.js";
import { explain } from "./explain.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCAN = join(HERE, "..", "..", "reprod", "out", "scan.json");
const ENV = join(HERE, "..", "..", "..", ".env");

/** Minimal .env loader — no dependency, and it must never overwrite a real env. */
function loadEnv(): void {
  if (!existsSync(ENV)) return;
  for (const line of readFileSync(ENV, "utf8").split(/\r?\n/u)) {
    const m = /^([A-Z0-9_]+)=(.*)$/u.exec(line.trim());
    if (m && process.env[m[1]!] === undefined) process.env[m[1]!] = m[2]!;
  }
}

const log = (s = ""): void => void process.stdout.write(`${s}\n`);

const GLYPH: Record<string, string> = { BLOCKER: "✗", WARNING: "!", NOTE: "·" };

function render(f: Finding): void {
  log(`  [${GLYPH[f.severity] ?? "·"}] ${f.severity.padEnd(7)} ${f.title}`);
  log(`      observed: ${f.observed}`);
  if (f.fix) log(`      fix:      ${f.fix}`);
  if (f.source) log(`      source:   ${f.source}`);
  log();
}

async function report(m: MachineFacts): Promise<void> {
  const findings = diagnose(m);
  log(`\n── ${m.teeId} ──`);
  log(`   extension ${m.extensionId} · ${m.status} · ${m.platform || "(no platform)"} · ${m.host}`);
  log(`   verdict: ${verdictOf(findings)}\n`);
  for (const f of findings) render(f);

  const e = await explain(findings);
  if (e.ok) {
    log(`   ── in plain English (generated by ${e.model} on 0G, not evidence) ──`);
    for (const line of (e.text ?? "").split("\n")) log(`   ${line}`);
  } else {
    log(`   (no prose: ${e.reason})`);
  }
}

async function main(): Promise<void> {
  loadEnv();

  if (!existsSync(SCAN)) {
    log(`scan not found at ${SCAN} — run \`pnpm -C packages/reprod run scan\` first`);
    process.exit(2);
  }
  const scan = JSON.parse(readFileSync(SCAN, "utf8")) as { machines: MachineFacts[] };
  const arg = process.argv[2];

  if (!arg) {
    log("usage: doctor <teeId|host> | --worst [n]");
    process.exit(2);
  }

  if (arg === "--worst") {
    const n = Number(process.argv[3] ?? 3);
    // Rank by blocker count, then prefer machines on real hardware — a dead
    // simulator is someone's laptop; a dead production machine matters more.
    const ranked = scan.machines
      .map((m) => ({ m, blockers: diagnose(m).filter((f) => f.severity === "BLOCKER").length }))
      .filter((x) => x.blockers > 0)
      .sort(
        (a, b) =>
          b.blockers - a.blockers ||
          Number(a.m.platform === "TEST_PLATFORM") - Number(b.m.platform === "TEST_PLATFORM"),
      );
    log(`${ranked.length} of ${scan.machines.length} machines have at least one blocker`);
    for (const { m } of ranked.slice(0, n)) await report(m);
    return;
  }

  const needle = arg.toLowerCase();
  const hit = scan.machines.find(
    (m) => m.teeId.toLowerCase() === needle || m.host.toLowerCase() === needle,
  );
  if (!hit) {
    log(`no machine matching "${arg}" in the register`);
    process.exit(1);
  }
  await report(hit);
}

main().catch((e: unknown) => {
  log(`doctor failed: ${e instanceof Error ? e.stack : String(e)}`);
  process.exit(1);
});
